[versions]
kotlin = "2.2.0"
shadow = "8.1.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
johnrengelman-shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
